version: '3.8'
services:
  nightwatch-n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: nightwatch-n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=myuser
      - N8N_BASIC_AUTH_PASS=mypassword
    volumes:
      - ./dist:/home/node/.n8n/custom
    ports:
      - "5678:5678"
